/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WareHouse;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.WareHouseEnterprise;
import Business.Enterprise.WareHouseInventory;
import Business.GlobalWaste;
import Business.Organization.WareHouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IndustryWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jay
 */
public class IndustryAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndustryAnalyticsJPanel
     */
    JPanel userProcessContainer;

    UserAccount account;
    WareHouseOrganization wareHouseOrganization;
    Enterprise enterprise;
    EcoSystem business;

    IndustryAnalyticsJPanel(JPanel userProcessContainer, UserAccount account, WareHouseOrganization wareHouseOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.wareHouseOrganization = wareHouseOrganization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }

    public void populateTable() {
        int price = 0;
        int total = 0;
        DefaultTableModel dtm = (DefaultTableModel) tabletable.getModel();
        dtm.setRowCount(0);

        for (GlobalWaste gw : business.getWasteDirectory().getWasteList()) {
            for (WareHouseInventory wi : ((WareHouseEnterprise) enterprise).getInventoryDirectory().getInventoryList()) {
                for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                    if ((request instanceof IndustryWorkRequest)) {
                        if (((IndustryWorkRequest) request).getOrderResult().equals("Approved")) {
                            if (((IndustryWorkRequest) request).getName().equals(wi.getInventoryName())) {

                                Object[] row = new Object[5];
                                row[0] = wi;
                                row[1] = ((IndustryWorkRequest) request).getIndquantity();
                                row[2] = wi.getSellingPrice();
                                row[3] = gw.getPrice();
                                price = ((wi.getSellingPrice() - gw.getPrice()) * ((IndustryWorkRequest) request).getIndquantity());
                                wi.setProfit(price);
                                total += wi.getProfit();
                    
                                row[4] = wi.getProfit();
                                dtm.addRow(row);
                            }
                        }
                    }
                    
                }
            }
        }
        totalProfitlabel.setText(Integer.toString(total));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalProfitlabel = new javax.swing.JLabel();

        tabletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waste Name", "Price", "Selling Price", "Buying Price", "Profit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabletable);
        if (tabletable.getColumnModel().getColumnCount() > 0) {
            tabletable.getColumnModel().getColumn(0).setResizable(false);
            tabletable.getColumnModel().getColumn(1).setResizable(false);
            tabletable.getColumnModel().getColumn(2).setResizable(false);
            tabletable.getColumnModel().getColumn(3).setResizable(false);
            tabletable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Total Profit : -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(508, Short.MAX_VALUE)
                    .addComponent(totalProfitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(257, 257, 257)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(326, Short.MAX_VALUE)
                    .addComponent(totalProfitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(235, 235, 235)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletable;
    private javax.swing.JLabel totalProfitlabel;
    // End of variables declaration//GEN-END:variables
}
