/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.QualityAssuarance;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.QualityAssuaranceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jay
 */
public class QualityAssuranceInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QualityAssuranceInventoryJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private QualityAssuaranceOrganization qualityOrganisation;
    private Enterprise enterprise;
    private EcoSystem system;

    QualityAssuranceInventoryJPanel(JPanel userProcessContainer, UserAccount account, QualityAssuaranceOrganization qualityOrganisation, Enterprise enterprise, EcoSystem system) {
        initComponents(); 
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.qualityOrganisation = qualityOrganisation;
        this.enterprise = enterprise;
        this.system = system;
        populateInventoryTable();
    }

    
    public void populateInventoryTable()
    {
        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
        
        model.setRowCount(0);
       // System.out.println("enterprise"+enterprise.getName()+ enterprise.getWorkQueue().getWorkRequestList().size());
            for (WorkRequest work : enterprise.getWorkQueue().getWorkRequestList()){
                
                
                      Object[] row = new Object[3];
                      row[0] = work.getWasteName();
                      row[1] = work.getQuant();
                      row[2]=work.getQualityResult();
                      model.addRow(row);
                
                     
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waste Name", "Quantity", "Quality Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryTable);
        if (inventoryTable.getColumnModel().getColumnCount() > 0) {
            inventoryTable.getColumnModel().getColumn(0).setResizable(false);
            inventoryTable.getColumnModel().getColumn(1).setResizable(false);
            inventoryTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
