/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Manufacturer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.IndustryEnterprise;
import Business.Enterprise.IndustryInventory;
import Business.Organization.ManufacturerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IndustryWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashis
 */
public class ManageManufacturerInventory extends javax.swing.JPanel {
private JPanel userProcessContainer;
  private UserAccount account;
 private  ManufacturerOrganization manufacturerOrganization;
 private Enterprise enterprise;
 private EcoSystem system;
    /**
     * Creates new form ManageManufacturerInventory
     */
    

    ManageManufacturerInventory(JPanel userProcessContainer, UserAccount account, ManufacturerOrganization manufacturerOrganization, Enterprise enterprise, EcoSystem system) {
         initComponents();
         this.account=account;
         this.userProcessContainer=userProcessContainer;
         this.enterprise=enterprise;
         this.system=system;
         this.manufacturerOrganization=manufacturerOrganization;
         label.setText(Enterprise.EnterpriseType.Manufacturer.toString());
         
         populateRequestTable();
         //populateInventory();
    }

    
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();

        model.setRowCount(0);
        for (WorkRequest industryReq : enterprise.getWorkQueue().getWorkRequestList()) {
            if (industryReq instanceof IndustryWorkRequest) {
                Object[] row = new Object[4];
                row[0] = ((IndustryWorkRequest) industryReq);
                row[1] = ((IndustryWorkRequest) industryReq).getIndquantity();
                row[2] = ((IndustryWorkRequest) industryReq).getOrderResult();

                model.addRow(row);
            }
        }
    }
    public void populateInventory(){
     DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();

        model.setRowCount(0);
        for (WorkRequest industryReq : enterprise.getWorkQueue().getWorkRequestList()) {
            if (industryReq instanceof IndustryWorkRequest){
                IndustryEnterprise a = ((IndustryEnterprise) enterprise);
                for(IndustryInventory indus : a.getIndustryDirectory().getIndustoryList())
                {
                    indus.setIndustryWaste(((IndustryWorkRequest) industryReq).getName());
                    indus.setIndustryQuantity(((IndustryWorkRequest) industryReq).getIndquantity());
                    indus.setBuyingPrice(((IndustryWorkRequest) industryReq).getPrice());
                    
                    
                    Object[] row =new Object[4];
                    row[0] = indus;
                    row[1] = indus.getInventoryID();
                    row[2] = indus.getIndustryQuantity();
                    row[3]  =indus.getBuyingPrice();
                    model.addRow(row);
                }
            }
                }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        label = new javax.swing.JLabel();

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waste Name", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
