/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.IndustryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.WareHouseEnterprise;
import Business.Network.Network;
import Business.Organization.IndustryOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IndustryWorkRequest;

import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashis
 */
public class ApproveManufacturerRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private IndustryOrganisation industryOrganisation;
    private Enterprise enterprise;
    private EcoSystem business;

    /**
     * Creates new form ApproveManufacturerRequest
     */

    ApproveManufacturerRequest(JPanel userProcessContainer, UserAccount account, IndustryOrganisation industryOrganisation, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.industryOrganisation = industryOrganisation;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : industryOrganisation.getWorkQueue().getWorkRequestList()) {
            if (request instanceof IndustryWorkRequest) {
                Object[] row = new Object[4];
                row[0] = ((IndustryWorkRequest) request);
                row[1] = request.getSender().getEmployee().getName();

                row[2] = ((IndustryWorkRequest) request).getIndquantity();
                row[3] = ((IndustryWorkRequest) request).getOrderResult();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        acceptRequestBtn = new javax.swing.JButton();
        rejectRequestBtn = new javax.swing.JButton();

        refreshBtn.setBackground(new java.awt.Color(0, 0, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Quanitity", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        acceptRequestBtn.setText("Accept");
        acceptRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptRequestBtnActionPerformed(evt);
            }
        });

        rejectRequestBtn.setText("Reject");
        rejectRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(rejectRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rejectRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed

    }//GEN-LAST:event_refreshBtnActionPerformed

    private void acceptRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptRequestBtnActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row");
        } else {
            if(request instanceof IndustryWorkRequest){
            request.setReceiver(account);
            ((IndustryWorkRequest) request).setOrderResult("Request Sent");
            
            for (Network network : business.getNetworkList()) {
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if ((ent instanceof WareHouseEnterprise) && ((IndustryWorkRequest) request).getOrderResult().equals("Request Sent")) {

                        ent.getWorkQueue().getWorkRequestList().add(request);

                    }

                }
            }
            }
            populateTable();

        }

    }//GEN-LAST:event_acceptRequestBtnActionPerformed

    private void rejectRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectRequestBtnActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rejectRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptRequestBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton rejectRequestBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
