/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.IndustryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.QualityAssuarance;
import Business.Enterprise.QualityAssuarance;
import Business.Enterprise.WareHouseEnterprise;
import Business.Enterprise.WareHouseInventory;
import Business.GlobalWaste;
import Business.Network.Network;
import Business.Organization.IndustryOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IndustryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jay
 */
public class RequestWastetoWareHouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestWastetoQualityAssuranceJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private IndustryOrganisation industryOrganisation;
    private Enterprise enterprise;
    private EcoSystem business;

    RequestWastetoWareHouseJPanel(JPanel userProcessContainer, UserAccount account, IndustryOrganisation industryOrganisation, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.industryOrganisation = industryOrganisation;
        this.business = business;
        this.enterprise = enterprise;
        populateRequestTable();
        populateWaste();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);
        for (WorkRequest industryReq : account.getWorkQueue().getWorkRequestList()) {
            if (industryReq instanceof IndustryWorkRequest) {
                Object[] row = new Object[4];
                row[0] = ((IndustryWorkRequest) industryReq).getName();
                row[1] = ((IndustryWorkRequest) industryReq).getIndquantity();
                row[2] = industryReq.getStatus();

                model.addRow(row);
            }
        }
    }

    public void populateWaste() {

        wasteComboBox.removeAllItems();
        for (GlobalWaste global : business.getWasteDirectory().getWasteList()) {
            for (WorkRequest loadItems : enterprise.getWorkQueue().getWorkRequestList()) {
                if (loadItems.getWasteName().equals(global.getWasteNsme())) {
                    wasteComboBox.addItem(loadItems.getWasteName());
                    break;
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        wasteComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(requestTable);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Available Waste : -");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Qty : -");

        requestTestJButton.setText("Request Approval");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wasteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton))
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wasteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(backJButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(requestTestJButton)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        String name = wasteComboBox.getSelectedItem().toString();

        IndustryWorkRequest request = new IndustryWorkRequest();
        request.setName(name);
        request.setSender(account);
        request.setStatus("Sent");
        request.setIndquantity(Integer.parseInt(quantityTextField.getText()));
        if (quantityTextField.getText().equals("") || quantityTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a number");
        } else {
            request.setQuant(Integer.parseInt(quantityTextField.getText()));
        }

        //        cust.setQuantity(Integer.parseInt(quantityTextField.getText()));
        //        cust.setWasteName(wasteComboBox.getSelectedItem().toString());
        Enterprise org = null;
        for (Network network : business.getNetworkList()) {
            for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {

                if ((enterprise.getEnterpriseType().getValue().equals("Industry") && ent instanceof WareHouseEnterprise)) {
                    org = ent;
                    ent.getWorkQueue().getWorkRequestList().add(request);
                    System.out.println(request.getName());
                }
            }
            if (org != null) {
                // org.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
            }

            populateRequestTable();
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JComboBox wasteComboBox;
    // End of variables declaration//GEN-END:variables
}
