/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Logistic;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LogisticsOrganisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jay
 */
public class LogisticsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsWorkAreaJPanel
     */
   
    private JPanel userProcessContainer;
    private UserAccount account;
    private LogisticsOrganisation logisticsOrganisation;
    private Enterprise enterprise;
    private EcoSystem system;
    public LogisticsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LogisticsOrganisation logisticsOrganisation, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.logisticsOrganisation = logisticsOrganisation;
        this.system = system;
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestInventoryButton = new javax.swing.JButton();

        requestInventoryButton.setBackground(new java.awt.Color(0, 0, 255));
        requestInventoryButton.setText("Accept Inventory");
        requestInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestInventoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(requestInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(requestInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestInventoryButtonActionPerformed
        ApproveInventoryJPanel requestVaccinesJPanel = new ApproveInventoryJPanel(userProcessContainer,account,logisticsOrganisation,enterprise,system);
        userProcessContainer.add("ApproveInventoryRequestJPanel", requestVaccinesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_requestInventoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton requestInventoryButton;
    // End of variables declaration//GEN-END:variables
}
